name: Deploy Website to Hosting (FTP / cPanel)

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Sync & Deploy to Hosting
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Ambil Source Code dari GitHub
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: 🚀 Upload File ke Server Hosting via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftpupload.net
          username: if0_42682625
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: cktlampung.web.id/htdocs/
          exclude: |
            **/.git*
            **/.git*/**
            **/scratch/**
            **/.env.example
            **/README.md
            **/vercel.json
            **/*.ps1
            **/*.sh
